# ===================================================================
# 実行設定
# ===================================================================
run_settings:
  device: "cuda"
  warmup_runs: 5 # ウォームアップ実行回数
  timed_runs: 50 # 時間測定を行う実行回数
  batch_sizes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024] # 性能曲線を測定するためのバッチサイズリスト

# ===================================================================
# ベンチマークグループの定義
# ===================================================================
benchmark_groups:
  # ===== GPU演算系ベンチマークグループ =====
  - group_name: "gpu_compute"
    enabled: true
    benchmarks:
      # --- MatMul (計算律速) ---
      - name: "MatMul_Square_4096"
        layer_type: "MatMul"
        data_types: ["fp32", "fp16"]
        batch_sizes: [1] # グローバル設定を上書きしてバッチサイズ1でのみ実行
        parameters:
          variant: "StressTest_2D"
          shape_a: [4096, 4096]
          shape_b: [4096, 4096]

      - name: "MatMul_Batched_512"
        layer_type: "MatMul"
        data_types: ["fp32", "fp16"]
        parameters:
          variant: "Batched_3D"
          shape_a: [512, 512]
          shape_b: [512, 512]

      # --- Add (メモリ律速) ---
      - name: "Add_ShallowLayer"
        layer_type: "Add"
        data_types: ["fp32", "fp16"]
        parameters:
          shape: [64, 224, 224]

      - name: "Add_DeepLayer"
        layer_type: "Add"
        data_types: ["fp32", "fp16"]
        parameters:
          shape: [512, 28, 28]

      # --- CNN拡張 ---
      - name: "Conv_Standard_k3s1"
        layer_type: "Conv2d"
        data_types: ["fp32", "fp16"]
        parameters:
          input_shape: [256, 56, 56] # (C, H, W)
          in_channels: 256
          out_channels: 256
          kernel_size: 3
          stride: 1
          padding: 1

      - name: "Conv_Bottleneck_k1s1"
        layer_type: "Conv2d"
        data_types: ["fp32", "fp16"]
        parameters:
          input_shape: [256, 56, 56]
          in_channels: 256
          out_channels: 128
          kernel_size: 1
          stride: 1
          padding: 0 # k=1, s=1の場合、通常paddingは0

      - name: "Conv_Downsampling_k3s2"
        layer_type: "Conv2d"
        data_types: ["fp32", "fp16"]
        parameters:
          input_shape: [256, 56, 56]
          in_channels: 256
          out_channels: 512
          kernel_size: 3
          stride: 2
          padding: 1

      - name: "BatchNorm_Typical"
        layer_type: "BatchNorm2d"
        data_types: ["fp32", "fp16"]
        parameters:
          input_shape: [256, 56, 56]
          num_features: 256 # in_channels

      # --- Transformer拡張 ---
      - name: "MatMul_Attention_QK"
        layer_type: "MatMul"
        data_types: ["fp32", "fp16"]
        parameters:
          variant: "Batched_3D"
          shape_a: [197, 64]
          shape_b: [64, 197]

      - name: "LayerNorm_ViT"
        layer_type: "LayerNorm"
        data_types: ["fp32", "fp16"]
        parameters:
          normalized_shape: [768]
          input_shape: [197, 768]

      - name: "Softmax_Attention"
        layer_type: "Softmax"
        data_types: ["fp32", "fp16"]
        parameters:
          dim: -1 # 最後の次元でSoftmaxを適用
          input_shape: [12, 197, 197]

  # ======== データ転送系ベンチマークグループ ========
  - group_name: "data_transfer"
    enabled: true
    benchmarks:
      # --- Host-to-Device転送 ---
      - name: "H2D_Pageable_Bandwidth"
        benchmark_type: "communication_bandwidth"
        parameters:
          direction: "H2D"
          use_pinned_memory: false # ページング可能メモリを使用
          transfer_sizes_mb: [1, 4, 16, 64, 256, 512, 1024]

      - name: "H2D_Pinned_Bandwidth"
        benchmark_type: "communication_bandwidth"
        parameters:
          direction: "H2D"
          use_pinned_memory: true # 最適化されたピン止めメモリを使用
          transfer_sizes_mb: [1, 4, 16, 64, 256, 512, 1024]

      # --- Device-to-Host (D2H) 転送 ---
      - name: "D2H_Pageable_Bandwidth"
        benchmark_type: "communication_bandwidth"
        parameters:
          direction: "D2H"
          use_pinned_memory: false
          transfer_sizes_mb: [1, 4, 16, 64, 256, 512, 1024]

      - name: "D2H_Pinned_Bandwidth"
        benchmark_type: "communication_bandwidth"
        parameters:
          direction: "D2H"
          use_pinned_memory: true
          transfer_sizes_mb: [1, 4, 16, 64, 256, 512, 1024]

  # ===== ホスト計算系ベンチマークグループ =====
  - group_name: "host_compute"
    enabled: true
    benchmarks:
      - name: "Image_Preprocessing_Rate"
        parameters:
          # Factoryがどのベンチマーククラスを使うかを決定する
          domain: "image_classification"
          # 性能カーブを測定するためのワーカー数リスト
          num_workers: "auto"
          # ベンチマークで処理する画像の総数
          num_images: 1000
          # リサイズ後の画像サイズ
          image_size: [224, 224]
